version: '3'

services:
  frontend:
    build:
      context: ./frontend 
    ports:
      - "8501:8501"
    networks:
      - network-backend

      
  qdrant_server:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    network_mode: host
      
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000"
    networks: 
     - network-backend
    depends_on:
     - qdrant_server

networks:
  network-backend: